version: '3'
services:
    api: 
        build: .
        
        ports:
            - 8000:8000
        volumes:
            - ./:/usr/src/app:ro
        
        env_file:
          - ./.env
            